name: 'composite action'
description: 'Sample of a composite action'

inputs:
  who-to-greet:
    type: string
    default: world

runs:
  using: composite

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:

    # Runs a single command using the runners shell
    - name: Run a one-line script
      shell: bash
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      shell: bash
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - shell: bash
      run: >
        echo hey how are you doing ${{ inputs.who-to-greet }}?
